name: Sanity test of action

on:
  release:
    types: [published, edited]

jobs:
  test-action:
    name: Sanity test of action
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./
        with:
          version: ${{ github.event.release.tag_name }}
          date: ${{ github.event.release.published_at }}
          title: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}

      - name: Commit result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Add ${{ github.event.release.tag_name }}"
          git push
