on:
  release:
    types: [published, edited]

name: Update release notes

jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Checkout release notes
      uses: actions/checkout@v4
      with:
        repository: madleech/update-release-notes-changelog
        path: changelog
        token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
    - name: Install JS dependencies
      run: cd .github/actions/update-changelog && npm install
    - name: Add release to server release notes
      uses: ./.github/actions/update-changelog
      with:
        filename: changelog/sample_changelog.md
        version: ${{ github.event.release.tag_name }}
        date: ${{ github.event.release.published_at }}
        title: ${{ github.event.release.name }}
        body: ${{ github.event.release.body }}
    - name: Show result
      run: cat changelog/sample_changelog.md
    - name: Commit result
      run: |
        cd changelog
        ls -lA
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add *.md
        git commit -m "Add ${{ github.event.release.tag_name }}"
        git push
